CREATE DATABASE windows;
CREATE USER 'update'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'update'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE  info_windows (
mac VARCHAR(12) PRIMARY KEY NOT NULL,
name VARCHAR(12) NOT NULL,
username VARCHAR(20) NOT NULL,
time VARCHAR(20) NOT NULL,
status VARCHAR(20) NOT NULL,
download VARCHAR(3) NOT NULL
);

